import { PresetWorkflow } from './types';

export const PRESET_WORKFLOWS: PresetWorkflow[] = [
  {
    id: 'support-router',
    name: 'Customer Request Classifier',
    description: 'Routes incoming user messages to Support, Technical Escalation, or Sales based on AI decisions.',
    defaultInput: 'My application crashes with error 500 when I click on the checkout button on the payment page.',
    nodes: [
      {
        id: 'start-node',
        type: 'start',
        position: { x: 250, y: 50 },
        data: {
          label: 'Customer Request Received',
          inputKey: 'userMessage',
          inputDescription: 'Raw customer message or ticket body',
        },
      },
      {
        id: 'node-1',
        type: 'aiDecision',
        position: { x: 250, y: 180 },
        data: {
          label: 'Is Support Request?',
          prompt: 'Is this input a customer support or help query regarding a problem or question?',
          description: 'Evaluates if message is asking for help',
        },
      },
      {
        id: 'node-2',
        type: 'aiDecision',
        position: { x: 100, y: 340 },
        data: {
          label: 'Is Technical Issue?',
          prompt: 'Is this an urgent software bug, crash, API error, or code fault needing developer intervention?',
          description: 'Checks for technical bug signatures',
        },
      },
      {
        id: 'node-3',
        type: 'aiDecision',
        position: { x: 450, y: 340 },
        data: {
          label: 'Is Purchase / Sales Inquiry?',
          prompt: 'Is this user interested in pricing, buying subscriptions, upgrade packages, or demo requests?',
          description: 'Checks for sales intent',
        },
      },
      {
        id: 'action-escalate',
        type: 'action',
        position: { x: 20, y: 520 },
        data: {
          label: 'Escalate to Engineering',
          actionType: 'escalate',
          message: 'Flagged as high-priority tech bug. Ticket sent to PagerDuty & Slack #eng-bugs.',
        },
      },
      {
        id: 'action-support',
        type: 'action',
        position: { x: 220, y: 520 },
        data: {
          label: 'Assign to General Support',
          actionType: 'assign_ticket',
          message: 'Routed to Zendesk Support Queue for standard Tier-1 response.',
        },
      },
      {
        id: 'action-sales',
        type: 'action',
        position: { x: 420, y: 520 },
        data: {
          label: 'Assign to Sales Team',
          actionType: 'assign_ticket',
          message: 'Lead forwarded to HubSpot Sales Pipeline & Account Executive.',
        },
      },
      {
        id: 'action-general',
        type: 'action',
        position: { x: 620, y: 520 },
        data: {
          label: 'Log to General Inbox',
          actionType: 'log',
          message: 'Uncategorized request logged in general feedback database.',
        },
      },
    ],
    edges: [
      {
        id: 'e-start-1',
        source: 'start-node',
        target: 'node-1',
        animated: true,
        style: { stroke: '#94a3b8', strokeWidth: 2 },
      },
      {
        id: 'e-1-yes',
        source: 'node-1',
        sourceHandle: 'yes',
        target: 'node-2',
        label: 'YES',
        style: { stroke: '#22c55e', strokeWidth: 2.5 },
        labelStyle: { fill: '#15803d', fontWeight: 700 },
      },
      {
        id: 'e-1-no',
        source: 'node-1',
        sourceHandle: 'no',
        target: 'node-3',
        label: 'NO',
        style: { stroke: '#ef4444', strokeWidth: 2.5 },
        labelStyle: { fill: '#b91c1c', fontWeight: 700 },
      },
      {
        id: 'e-2-yes',
        source: 'node-2',
        sourceHandle: 'yes',
        target: 'action-escalate',
        label: 'YES',
        style: { stroke: '#22c55e', strokeWidth: 2.5 },
        labelStyle: { fill: '#15803d', fontWeight: 700 },
      },
      {
        id: 'e-2-no',
        source: 'node-2',
        sourceHandle: 'no',
        target: 'action-support',
        label: 'NO',
        style: { stroke: '#ef4444', strokeWidth: 2.5 },
        labelStyle: { fill: '#b91c1c', fontWeight: 700 },
      },
      {
        id: 'e-3-yes',
        source: 'node-3',
        sourceHandle: 'yes',
        target: 'action-sales',
        label: 'YES',
        style: { stroke: '#22c55e', strokeWidth: 2.5 },
        labelStyle: { fill: '#15803d', fontWeight: 700 },
      },
      {
        id: 'e-3-no',
        source: 'node-3',
        sourceHandle: 'no',
        target: 'action-general',
        label: 'NO',
        style: { stroke: '#ef4444', strokeWidth: 2.5 },
        labelStyle: { fill: '#b91c1c', fontWeight: 700 },
      },
    ],
  },
  {
    id: 'lead-qualification',
    name: 'B2B Lead Qualification',
    description: 'Determines if an incoming prospect is qualified for direct enterprise sales outreach.',
    defaultInput: 'We are an enterprise company with 250 employees and a budget of $50,000 looking to deploy custom AI workflows this quarter.',
    nodes: [
      {
        id: 'start-lead',
        type: 'start',
        position: { x: 250, y: 50 },
        data: {
          label: 'Prospect Submission',
          inputKey: 'prospectNotes',
          inputDescription: 'Submission details from contact form',
        },
      },
      {
        id: 'node-enterprise',
        type: 'aiDecision',
        position: { x: 250, y: 180 },
        data: {
          label: 'Is Enterprise Scale?',
          prompt: 'Does this prospect indicate enterprise or mid-market team size (e.g. over 50 employees or high volume operational need)?',
        },
      },
      {
        id: 'node-budget',
        type: 'aiDecision',
        position: { x: 100, y: 340 },
        data: {
          label: 'Has Adequate Budget?',
          prompt: 'Does the message express or imply an adequate budget (over $10k or enterprise readiness)?',
        },
      },
      {
        id: 'action-hot-lead',
        type: 'action',
        position: { x: 20, y: 500 },
        data: {
          label: 'Book Priority Demo',
          actionType: 'notification',
          message: 'Qualified High Intent Lead! Triggering automated Calendly invite & Slack alert.',
        },
      },
      {
        id: 'action-nurture',
        type: 'action',
        position: { x: 250, y: 500 },
        data: {
          label: 'Add to Email Nurture',
          actionType: 'log',
          message: 'Add lead to automated drip marketing sequence.',
        },
      },
    ],
    edges: [
      {
        id: 'e-lead-1',
        source: 'start-lead',
        target: 'node-enterprise',
        animated: true,
      },
      {
        id: 'e-ent-yes',
        source: 'node-enterprise',
        sourceHandle: 'yes',
        target: 'node-budget',
        label: 'YES',
        style: { stroke: '#22c55e', strokeWidth: 2.5 },
      },
      {
        id: 'e-ent-no',
        source: 'node-enterprise',
        sourceHandle: 'no',
        target: 'action-nurture',
        label: 'NO',
        style: { stroke: '#ef4444', strokeWidth: 2.5 },
      },
      {
        id: 'e-bud-yes',
        source: 'node-budget',
        sourceHandle: 'yes',
        target: 'action-hot-lead',
        label: 'YES',
        style: { stroke: '#22c55e', strokeWidth: 2.5 },
      },
      {
        id: 'e-bud-no',
        source: 'node-budget',
        sourceHandle: 'no',
        target: 'action-nurture',
        label: 'NO',
        style: { stroke: '#ef4444', strokeWidth: 2.5 },
      },
    ],
  },
];